# Generated by Django 5.1.7 on 2025-03-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshortener", "0002_mylink_expiration_date_alter_mylink_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clickanalytics",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
